FROM streaming-search-base:latest

WORKDIR /app
COPY . /app

# install project deps
RUN uv sync --no-dev

EXPOSE 8000
CMD ["uv", "run", "python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
