FROM streaming-search-base:latest
WORKDIR /app
COPY . /app

ENV PYTHONPATH="/app/src"
EXPOSE 8501

CMD ["streamlit","run","dashboard/metaflow_dashboard.py","--server.address","0.0.0.0","--server.port","8501"]
